<?php
// ensures that all configuration constants are defined with default values
define_once('__CLEMENTINE_JSTOOLS_CKEDITOR_PGRFILEMANAGER_FILEMAXSIZE__', 1024 * 1024 * 10);
define_once('__CLEMENTINE_JSTOOLS_CKEDITOR_PGRFILEMANAGER_ALLOWEDEXTENSIONS__', '');
define_once('__CLEMENTINE_JSTOOLS_CKEDITOR_PGRFILEMANAGER_IMAGEEXTENSIONS__', 'jpg|gif|jpeg|png|bmp');
define_once('__CLEMENTINE_JSTOOLS_CKEDITOR_PGRFILEMANAGER_IMAGEMAXWIDTH__', 1280);
define_once('__CLEMENTINE_JSTOOLS_CKEDITOR_PGRFILEMANAGER_IMAGEMAXHEIGHT__', 1024);
?>
